### ISSUE TITLE
Responsive landing page doesn't work

### ISSUE THREAD

**Issue by DaniNz** [Trackear/trackear#19]
**Describe the bug**
The landing page doesn't adapt to mobile devices' screen sizes.

**To Reproduce**
1. Go to '[landing page'](https://www.trackear.app/)
2. Click on 'F12'
4. Click on the 'Responsive Desing tool'.
5. Pick a Mobile screen size.
6. See how the entire page messes up.

**Expected behavior**
The page should adapt the layout according to the size of the device being displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16692007/103722776-7e31dc00-4faf-11eb-9ae2-3ab91fac8d6d.png)
![image](https://user-images.githubusercontent.com/16692007/103722896-b5a08880-4faf-11eb-9713-8e74ade4e434.png)
![image](https://user-images.githubusercontent.com/16692007/103722971-d4068400-4faf-11eb-839c-f44bb6f1f3f7.png)

**Comment by Ruk33** [comment]
Merged and deployed!
