### ISSUE TITLE
Landing page: Trackear icon color and navbar text-color

### ISSUE THREAD

**Issue by DaniNz** [Trackear/trackear#20]
**Describe the bug**
The icon and the texts are not very clear due to the new background-color.

**To Reproduce**
Go to the [Landing page](https://www.trackear.app).

**Screenshots**
Icon
![image](https://user-images.githubusercontent.com/16692007/103729714-cc4edb80-4fbf-11eb-807e-f80feae6a509.png)

Navbar
![image](https://user-images.githubusercontent.com/16692007/103730378-7da24100-4fc1-11eb-97b7-4a71bd1dacff.png)

**Comment by Ruk33** [comment]
Deployed. Thanks!
