### ISSUE TITLE
Sign up error message: when the passwords don't match

### ISSUE THREAD

**Issue by DaniNz** [Trackear/trackear#38]
**Describe the bug**
sign up error message: when the passwords don't match

**To Reproduce**
1. Go to sing up form
2. fill all the fields but make that the passwords don't match
3. submit

**Screenshots**
![image](https://user-images.githubusercontent.cSign upom/16692007/104827095-15f9ba80-5839-11eb-8167-f34a28822224.png)

**Comment by Ruk33** [comment]
No longer applies with the new deploy of auth. Closing.
